### ISSUE TITLE
Notice: Undefined index: id - AdminLiteSpeedCacheConfigController

### ISSUE THREAD

**Issue by pmartin-webimpacto** [litespeedtech/lscache_prestashop#46]
With Debug Mode: ON
Controller: AdminLiteSpeedCacheConfigController 
Prestashop: 1.7.8.1
PHP: 7.4 

![image](https://user-images.githubusercontent.com/16488733/143785440-f8499dce-335c-4b29-a23f-7c14281cdd89.png)

**Comment by litespeedtech** [comment]
this is fixed in v1.4.1
