### ISSUE TITLE
ESI public block issue

### ISSUE THREAD

**Issue by Triloworld** [litespeedtech/lscache_prestashop#48]
Error somewhere in plugin properly use ESI block feature.

Occur: Randomly. Different theme. If engine run clear cache more than one time then is more frequent

Our shop:
![Screenshot_20221124-163221_Chrome](https://user-images.githubusercontent.com/2671726/203824427-2c5a2eff-ee46-4467-aec3-4919c95f4174.jpg)

Client using this:
https://www.google.com/search?q=_LSCESI&oq=_LSCESI&aqs=chrome.0.69i59j35i39.7522j0j7&sourceid=chrome&ie=UTF-8
(you can search by this phrase)

**Comment by litespeedtech** [comment]
If you can still reproduce this with 1.4.1, please create a ticket and we'll follow up.
Sorry for late reply.

**Comment by Triloworld** [comment]
Yes. It was fixes. We do flush few times. I will re-open and write there if that will be the case. Thank you.
