### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by therampagerado** [litespeedtech/lscache_prestashop#49]
Message:
Array to string conversion

Location:
modules/litespeedcache/classes/Cache.php line 501

#0  modules/litespeedcache/classes/Cache.php(501)
#1  modules/litespeedcache/classes/Cache.php(588): LiteSpeedCacheCore->getPurgeTagsByCategory(Category#1)
#2  modules/litespeedcache/classes/Cache.php(511): LiteSpeedCacheCore->getPurgeTagsByHookMethod("hookactionCategoryUpdate", array(4))
#3  modules/litespeedcache/litespeedcache.php(302): LiteSpeedCacheCore->purgeByCatchAllMethod("hookactionCategoryUpdate", array(4))
#4  classes/Hook.php(744): LiteSpeedCache->__call("hookactionCategoryUpdate", array(4))
#5  override/classes/Hook.php(43): HookCore::coreCallHook(LiteSpeedCache#1, "hookactionCategoryUpdate", array(4))
#6  classes/Hook.php(458): Hook::coreCallHook(LiteSpeedCache#1, "hookactionCategoryUpdate", array(4))
#7  classes/Hook.php(282): HookCore::execWithoutCache("actionCategoryUpdate", array(4), null, false, true, false, null)
#8  classes/Category.php(1458): HookCore::exec("actionCategoryUpdate", array(1))
#9  classes/controller/AdminController.php(1292): CategoryCore->update()
#10 classes/controller/AdminController.php(1249): AdminControllerCore->processUpdate()
#11 classes/controller/AdminController.php(601): AdminControllerCore->processSave()
#12 controllers/admin/AdminCategoriesController.php(807): AdminControllerCore->postProcess()
#13 classes/controller/Controller.php(191): AdminCategoriesControllerCore->postProcess()
#14 classes/Dispatcher.php(851): ControllerCore->run()
#15 adminXXXX/index.php(58): DispatcherCore->dispatch()

**Comment by litespeedtech** [comment]
please try with latest 1.4.1, see if you still have issues.

**Comment by therampagerado** [comment]
Just installed it in two shops. Will give feedback soon. Thanks! Hopefully the module will receive some nice features from WP as now it seems supported again!

**Comment by therampagerado** [comment]
Unfortunately the error is still here:

![image](https://github.com/litespeedtech/lscache_prestashop/assets/11251370/848bd745-e00a-4844-991f-f4142849bb8c)
