### ISSUE TITLE
Update compatibility

### ISSUE THREAD

**Issue by matrixino** [litespeedtech/lscache_prestashop#52]
Hello all,
I'm wondering if this project is still maintained. The latest module version in dated 2020 and won't install/work on the latest versions of Prestashop (PS1.7.8+ and PS8+). Any chance to get this working again?

**Comment by matrixino** [comment]
> Hi I use it with 1.7.8.7 and i don't have any bug with it.

Not sure which minor 1.7.8 was it. Did you try on 8?

**Comment by litespeedtech** [comment]
Should be fixed in latest release 1.4.1
