### ISSUE TITLE
[PHP Unknown error #8192] Return type of LiteSpeedCacheEsiModConf::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice (/home/xyzwert/public_html/modules/litespeedcache/classes/EsiModConf.php, line 146) (#CON11)

### ISSUE THREAD

**Issue by radiogena** [litespeedtech/lscache_prestashop#64]
I am trying to connect fresh installed Prestashop 8.1.5 through API to external ERP system. Installed LiteSpeed Cache Plugin
v1.4.1 - by LiteSpeedTech. PHP version: 8.1.28.

getting this error:

[PHP Unknown error #8192] Return type of LiteSpeedCacheEsiModConf::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice (/home/xyzwert/public_html/modules/litespeedcache/classes/EsiModConf.php, line 146) (#CON11)

any solution how to fix it?

**Comment by soyjosean** [comment]
You can apply this patch to fix the problem:
https://github.com/litespeedtech/lscache_prestashop/commit/4ce716dd97461cdd36e0b4a25f03894538e079fe

**Comment by radiogena** [comment]
after the patch pop-up another error below:

[PHP Unknown error #8192] preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated (/home/eypppvhr/public_html/modules/litespeedcache/classes/EsiModConf.php, line 250) (#CON11)
